export const teams = [
  { id: "1", name: "1. Herren", club: "FSV Hansa 07 Kreuzberg" },
  { id: "2", name: "2. Herren", club: "FSV Hansa 07 Kreuzberg" },
  { id: "3", name: "3. Herren", club: "FSV Hansa 07 Kreuzberg" },
  { id: "4", name: "1. Frauen", club: "FSV Hansa 07 Kreuzberg" },
  { id: "5", name: "2. Frauen", club: "FSV Hansa 07 Kreuzberg" },
  { id: "6", name: "7er Frauen", club: "FSV Hansa 07 Kreuzberg" },
  { id: "7", name: "G-Jugend", club: "FSV Hansa 07 Kreuzberg" },
  { id: "8", name: "F-Jugend", club: "FSV Hansa 07 Kreuzberg" },
  { id: "9", name: "D-Jugend", club: "FSV Hansa 07 Kreuzberg" },
  { id: "10", name: "C-Jugend", club: "FSV Hansa 07 Kreuzberg" },
  { id: "11", name: "B-Jugend", club: "FSV Hansa 07 Kreuzberg" },
  { id: "12", name: "A-Jugend", club: "FSV Hansa 07 Kreuzberg" },
  { id: "13", name: "Ü32 Senioren", club: "FSV Hansa 07 Kreuzberg" },
  { id: "14", name: "Ü40 Senioren", club: "FSV Hansa 07 Kreuzberg" },
];

export const pitches = [
  {
    id: "0",
    slug: "lobeckplatz",
    name: "Lobeckplatz",
    gps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
  },
  {
    id: "1",
    slug: "sportplatz-wiener-strasse",
    name: "Sportplatz Wiener Straße",
    gps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
  },
  {
    id: "2",
    slug: "sportplatz-zullichauer-strasse",
    name: "Sportplatz Züllichauer Straße",
    gps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
  },
];

export const availableSlots = [
  {
    id: "0",
    time: "04:00 PM",
    day: "Monday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "1",
    time: "05:30 PM",
    day: "Monday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "2",
    time: "07:00 PM",
    day: "Monday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "3",
    time: "08:30 PM",
    day: "Monday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "4",
    time: "04:00 PM",
    day: "Tuesday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "5",
    time: "05:30 PM",
    day: "Tuesday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "6",
    time: "07:00 PM",
    day: "Tuesday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "7",
    time: "08:30 PM",
    day: "Tuesday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "8",
    time: "04:00 PM",
    day: "Wednesday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "9",
    time: "05:30 PM",
    day: "Wednesday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "10",
    time: "07:00 PM",
    day: "Wednesday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "11",
    time: "08:30 PM",
    day: "Wednesday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "12",
    time: "04:00 PM",
    day: "Thursday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "13",
    time: "05:30 PM",
    day: "Thursday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "14",
    time: "07:00 PM",
    day: "Thursday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "15",
    time: "08:30 PM",
    day: "Thursday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "16",
    time: "04:00 PM",
    day: "Friday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "17",
    time: "05:30 PM",
    day: "Friday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "18",
    time: "07:00 PM",
    day: "Friday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "19",
    time: "08:30 PM",
    day: "Friday",
    locationName: "Sportplatz Wiener Straße",
    locationSlug: "sportplatz-wiener-strasse",
    locationGps: "https://maps.app.goo.gl/5vgGMZiRxZfJxFs26",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "20",
    time: "04:00 PM",
    day: "Monday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "21",
    time: "05:30 PM",
    day: "Monday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "22",
    time: "07:00 PM",
    day: "Monday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "23",
    time: "08:30 PM",
    day: "Monday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "24",
    time: "04:00 PM",
    day: "Tuesday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "25",
    time: "05:30 PM",
    day: "Tuesday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "26",
    time: "07:00 PM",
    day: "Tuesday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "27",
    time: "08:30 PM",
    day: "Tuesday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "28",
    time: "04:00 PM",
    day: "Wednesday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "29",
    time: "05:30 PM",
    day: "Wednesday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "30",
    time: "07:00 PM",
    day: "Wednesday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "31",
    time: "08:30 PM",
    day: "Wednesday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "32",
    time: "04:00 PM",
    day: "Thursday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "33",
    time: "05:30 PM",
    day: "Thursday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "34",
    time: "07:00 PM",
    day: "Thursday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "35",
    time: "08:30 PM",
    day: "Thursday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "36",
    time: "04:00 PM",
    day: "Friday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "37",
    time: "05:30 PM",
    day: "Friday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "38",
    time: "07:00 PM",
    day: "Friday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "39",
    time: "08:30 PM",
    day: "Friday",
    locationName: "Lobeckplatz",
    locationSlug: "lobeckplatz",
    locationGps: "https://maps.app.goo.gl/YoUyrNTxnu6jWSaH7",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "40",
    time: "04:00 PM",
    day: "Monday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "41",
    time: "05:30 PM",
    day: "Monday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "42",
    time: "07:00 PM",
    day: "Monday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "43",
    time: "08:30 PM",
    day: "Monday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "44",
    time: "04:00 PM",
    day: "Tuesday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "45",
    time: "05:30 PM",
    day: "Tuesday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "46",
    time: "07:00 PM",
    day: "Tuesday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "47",
    time: "08:30 PM",
    day: "Tuesday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "48",
    time: "04:00 PM",
    day: "Wednesday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "DFC Kreuzberg",
  },
  {
    id: "49",
    time: "05:30 PM",
    day: "Wednesday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "50",
    time: "07:00 PM",
    day: "Wednesday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "51",
    time: "08:30 PM",
    day: "Wednesday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "52",
    time: "04:00 PM",
    day: "Thursday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "53",
    time: "05:30 PM",
    day: "Thursday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "54",
    time: "07:00 PM",
    day: "Thursday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "55",
    time: "08:30 PM",
    day: "Thursday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "56",
    time: "04:00 PM",
    day: "Friday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "57",
    time: "05:30 PM",
    day: "Friday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
  {
    id: "58",
    time: "07:00 PM",
    day: "Friday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "FSV Hansa 07 Kreuzberg",
  },
  {
    id: "59",
    time: "08:30 PM",
    day: "Friday",
    locationName: "Sportplatz Züllichauer Straße",
    locationSlug: "sportplatz-zullichauer-strasse",
    locationGps: "https://maps.app.goo.gl/U3NQr5WFUFW4peSg9",
    isAvailable: true,
    clubName: "Berliner Amateure",
  },
];
